#pragma once

#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS

#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 50

#define RGB_MATRIX_TIMEOUT 60000
